---
version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: playground
    volumes:
      - "./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
  go:
    image: golang:1.11.1
    volumes:
      - ".:/src/github.com/hkdnet/go-mysql-what-if"
    working_dir: "/src/github.com/hkdnet/go-mysql-what-if"
    command: make test
    links:
      - mysql
